//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MACU_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_FaJournal
    {
        public int Id { get; set; }
        public string SubpType { get; set; }
        public string DebitAmount { get; set; }
        public string CreditAmount { get; set; }
        public string CurrencyName { get; set; }
        public string FiscalYear { get; set; }
        public string AccountPeriod { get; set; }
        public string GUID { get; set; }
        public string SubpDate { get; set; }
        public string SubpNo { get; set; }
        public string SubpSummary { get; set; }
        public string SubjectName { get; set; }
        public string AccountNo { get; set; }
        public string DetailAccountNo { get; set; }
        public string DetailSubjectName { get; set; }
        public string DepartNo { get; set; }
        public string DepartName { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectAbbr { get; set; }
        public string ObjectCateg { get; set; }
        public string ObjectNo { get; set; }
        public string CurrencyNo { get; set; }
        public string ExchangeRate { get; set; }
        public string OriginCurrency { get; set; }
        public string LocalCurrencyAmount { get; set; }
        public string Spare1No { get; set; }
        public string Spare1Abbr { get; set; }
        public string Spare2No { get; set; }
        public string Spare2Abbr { get; set; }
        public string Spare3No { get; set; }
        public string Spare3Abbr { get; set; }
        public string Spare4No { get; set; }
        public string Spare4Abbr { get; set; }
        public string Spare5No { get; set; }
        public string Spare5Abbr { get; set; }
        public string Summary1 { get; set; }
        public string AccountSubjects { get; set; }
        public string Summary { get; set; }
        public string Category { get; set; }
        public string SubjectAlias { get; set; }
        public int IsValid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
