//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MACU_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_JournalV1
    {
        public int Id { get; set; }
        public string SubpDate { get; set; }
        public string SubpNo { get; set; }
        public string AccountNo { get; set; }
        public string SubjectName { get; set; }
        public string DetailAccountNo { get; set; }
        public string DetailSubjectName { get; set; }
        public string DepartNo { get; set; }
        public string DepartName { get; set; }
        public string DebitAmount { get; set; }
        public string CreditAmount { get; set; }
        public Nullable<int> IsValid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string FiscalYear { get; set; }
        public string AccountPeriod { get; set; }
    }
}
