//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MACU_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_LaborInsSet
    {
        public int Id { get; set; }
        public string LabInsSetNo { get; set; }
        public Nullable<decimal> OrdAccidentInsRate { get; set; }
        public Nullable<decimal> EmployInsRate { get; set; }
        public Nullable<decimal> PersonalInsRate { get; set; }
        public Nullable<decimal> LaborBurdenRatio { get; set; }
        public Nullable<decimal> ComBurdenRatio { get; set; }
        public Nullable<decimal> GovBurdenRatio { get; set; }
        public Nullable<decimal> CommuteDisaInsRate { get; set; }
        public Nullable<decimal> IndustryDisaInsRate { get; set; }
        public Nullable<decimal> OccuDisaInsRate { get; set; }
        public Nullable<decimal> OccuDisComBurdenRatio { get; set; }
        public string OnBeginDate { get; set; }
        public Nullable<decimal> LaborRetireRate { get; set; }
        public Nullable<decimal> LaborSubsFund { get; set; }
        public Nullable<decimal> LaborSubsFundRate { get; set; }
        public Nullable<int> IsValid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
