//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MACU_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_LaborHealthInsV1
    {
        public int Id { get; set; }
        public string DepartName { get; set; }
        public string PlusInsCompany { get; set; }
        public string MemberName { get; set; }
        public string LaborIns { get; set; }
        public string HealthIns { get; set; }
        public string Dependents { get; set; }
        public string OnJobDate { get; set; }
        public string ResignDate { get; set; }
        public string DataYear { get; set; }
        public string DataMonth { get; set; }
        public int IsValid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> LHInsType { get; set; }
    }
}
