//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MACU_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MERPEntities : DbContext
    {
        public MERPEntities()
            : base("name=MERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileContent> FileContent { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<FA_ClassInfo> FA_ClassInfo { get; set; }
        public virtual DbSet<ProgContent> ProgContent { get; set; }
        public virtual DbSet<FA_FaJournal> FA_FaJournal { get; set; }
        public virtual DbSet<FA_JournalV1> FA_JournalV1 { get; set; }
        public virtual DbSet<AccountInfo> AccountInfo { get; set; }
        public virtual DbSet<HR_ManagerInfo> HR_ManagerInfo { get; set; }
        public virtual DbSet<StoreInfo> StoreInfo { get; set; }
        public virtual DbSet<FA_LaborHealthIns> FA_LaborHealthIns { get; set; }
        public virtual DbSet<FA_HealthInsSet> FA_HealthInsSet { get; set; }
        public virtual DbSet<FA_LaborHealthInsV1> FA_LaborHealthInsV1 { get; set; }
        public virtual DbSet<FA_LaborSubsFundSet> FA_LaborSubsFundSet { get; set; }
        public virtual DbSet<FA_LaborInsSet> FA_LaborInsSet { get; set; }
        public virtual DbSet<FA_LaborInsSetMapComSet> FA_LaborInsSetMapComSet { get; set; }
        public virtual DbSet<StoreGroupSet> StoreGroupSet { get; set; }
    }
}
